version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nodetest-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nodetest-frontend
    ports:
      - "5173:80"
    restart: always
