FROM nvidia/cuda:12.2.0-base-ubuntu22.04

WORKDIR /app

RUN apt-get update && \
    apt-get install -y ffmpeg python3 python3-pip git curl && \
    rm -rf /var/lib/apt/lists/*

COPY backend/package*.json ./
RUN npm install

COPY backend/. .

EXPOSE ${PORT}
CMD ["npm", "start"]
