version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodetest-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nodetest-frontend
    ports:
      - "3000:80"
