version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: ai_backend
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./Backend/generated:/app/generated
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: ai_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
